### ISSUE TITLE
convert fetch_stuff to fetch

### ISSUE THREAD

**Issue by ghost** [L-Sherry/Localize-me#6]
![image](https://user-images.githubusercontent.com/13393678/82130547-f3873d00-9791-11ea-8864-7c5bdc6cb3d9.png)
It seems like making a promise with XMLHttpRequest is pointless when fetch exists.

**Comment by L-Sherry** [comment]
You mean like this ? 94404cd3c6a1c5b911bac932adc85832060dd495

**Comment by ghost** [comment]
Yes. I did not see v1.x
